/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene-transformed.glb --shadows
Author: 3Dee (https://sketchfab.com/mellydeeis)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sound-system-db6b704527404c25b0da257270630508
Title: Sound System
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Speaker(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')

  console.log("in peaker", )
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} position={[-194.89, 118.57, -112.53]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 87.41, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube001_Material_0.geometry} material={materials.Material} position={[-192.94, 157.26, -83.27]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 87.41, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube002_Material003_0.geometry} material={materials['Material.003']} position={[-194.94, 65.12, -113.29]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 87.41, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube003_Material002_0.geometry} material={materials['Material.002']} position={[-199.23, 27.45, -177.66]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 67.88, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube004_Material004_0.geometry} material={materials['Material.004']} position={[-196.17, 285.28, -131.65]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 87.41, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube005_Material005_0.geometry} material={materials['Material.005']} position={[-196.52, 366.84, -136.97]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 68.77, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube007_Material005_0.geometry} material={materials['Material.005']} position={[-196.86, 366.72, -146.36]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 68.77, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube010_Material006_0.geometry} material={materials['Material.005']} position={[-196.09, 431.27, -130.45]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[63.62, 41.57, 63.62]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Circle_Material008_0.geometry} material={materials['Material.008']} position={[-191.97, 183, -70.81]} rotation={[0, 0.07, 0]} scale={44.26} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Circle002_Material007_0.geometry} material={materials['Material.007']} position={[-192.15, 183, -73.5]} rotation={[0, 0.07, 0]} scale={44.26} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Cube006_Material_0.geometry} material={materials.Material} position={[-192.23, 287.03, -72.51]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[100, 87.41, 100]} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Circle004_Material008_0.geometry} material={materials['Material.008']} position={[-192.01, 287.25, -71.47]} rotation={[0, 0.07, 0]} scale={44.26} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Circle005_Material007_0.geometry} material={materials['Material.007']} position={[-192.12, 287.25, -73.09]} rotation={[0, 0.07, 0]} scale={44.26} /> */}
        {/* <mesh castShadow receiveShadow geometry={nodes.Circle006_Material009_0.geometry} material={materials['Material.009']} position={[-191.89, 183, -69.62]} rotation={[0, 0.07, 0]} scale={44.26} /> */}
        <mesh castShadow receiveShadow geometry={nodes.Cube008_Material001_0.geometry} material={materials['Material.001']} position={[182.45, 118.57, -79.22]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 87.41, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube009_Material_0.geometry} material={materials.Material} position={[177.68, 157.26, -50.29]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 87.41, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube011_Material003_0.geometry} material={materials['Material.003']} position={[182.58, 65.12, -79.98]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 87.41, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube012_Material002_0.geometry} material={materials['Material.002']} position={[193.08, 27.45, -143.62]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 67.88, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_Material004_0.geometry} material={materials['Material.004']} position={[185.57, 285.28, -98.13]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 87.41, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube014_Material005_0.geometry} material={materials['Material.005']} position={[186.44, 366.84, -103.39]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 68.77, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube015_Material005_0.geometry} material={materials['Material.005']} position={[188.25, 366.72, -112.61]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 68.77, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_Material006_0.geometry} material={materials['Material.005']} position={[185.38, 431.27, -96.94]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[63.62, 41.57, 63.62]} />
        <mesh castShadow receiveShadow geometry={nodes.Circle007_Material008_0.geometry} material={materials['Material.008']} position={[175.78, 183, -37.94]} rotation={[0, -0.16, 0]} scale={44.26} />
        <mesh castShadow receiveShadow geometry={nodes.Circle009_Material007_0.geometry} material={materials['Material.007']} position={[176.22, 183, -40.6]} rotation={[0, -0.16, 0]} scale={44.26} />
        <mesh castShadow receiveShadow geometry={nodes.Cube017_Material_0.geometry} material={materials.Material} position={[175.92, 287.03, -39.65]} rotation={[-Math.PI / 2, 0, -0.16]} scale={[100, 87.41, 100]} />
        <mesh castShadow receiveShadow geometry={nodes.Circle011_Material008_0.geometry} material={materials['Material.008']} position={[175.89, 287.25, -38.59]} rotation={[0, -0.16, 0]} scale={44.26} />
        <mesh castShadow receiveShadow geometry={nodes.Circle012_Material007_0.geometry} material={materials['Material.007']} position={[176.15, 287.25, -40.19]} rotation={[0, -0.16, 0]} scale={44.26} />
        <mesh castShadow receiveShadow geometry={nodes.Circle013_Material009_0.geometry} material={materials['Material.009']} position={[175.59, 183, -36.76]} rotation={[0, -0.16, 0]} scale={44.26} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
